language: generic
sudo: false

env:
- RESOLVER=lts-2
- RESOLVER=lts-3
- RESOLVER=lts-6
- RESOLVER=lts-7
- RESOLVER=lts-9
- RESOLVER=lts-11
- RESOLVER=lts-12
os:
- linux
- osx

addons:
  apt: 
    packages: [libgmp-dev]

matrix:
  exclude:
  - env: RESOLVER=lts-2
    os: osx
before_install:
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

script:
- stack --resolver=$RESOLVER --no-terminal test --ghc-options=-Werror

cache:
  directories:
    - '$HOME/.stack'
